### ISSUE TITLE
Cannot convert csv into datafile

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#27] opened 2019-12-02 08:22 UTC
Hello,

I installed Otoole using the Anaconda prompt, as suggested in the repository.

I am trying to convert csv into datafile (from Simplicity). I do it by first activating "myenv" in Anaconda, then call Otoole the following way:

otoole convert csv datafile <frompath> <topath>

But the conversion cannot be carried out. The following message pops up:

```python
Traceback (most recent call last):
  File "c:\users\lats1\anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lats1\anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LATS1\Anaconda3\envs\myenv\Scripts\otoole.exe\__main__.py", line 7, in <module>
  File "c:\users\lats1\anaconda3\envs\myenv\lib\site-packages\otoole\cli.py", line 191, in main
    args.func(args)
  File "c:\users\lats1\anaconda3\envs\myenv\lib\site-packages\otoole\cli.py", line 111, in conversion_matrix
    raise NotImplementedError(msg)
NotImplementedError: Conversion from csv to datafile is not yet implemented
```
Can you please help me?

Thank you, 

Luiscarlos

_Originally posted by @LuiscarlosTorres in https://github.com/OSeMOSYS/otoole/issues/26#issuecomment-560083930_

**Comment by willu47** [comment] 2019-12-02 08:27
Hi @LuiscarlosTorres - I created a new issue with your question.

Conversion from a folder of CSV files (with each file named as an OSeMOSYS parameter) directly to a datafile is not yet implemented.  If this *is* what you want to do, then you should 

1. convert to a datapackage `otoole convert csv datapackage <my_folder> <datapackage_name>` and then
2. from a data package to a datafile `otoole convert datapackage datafile <datapackage name> <datafile_name>`

However, if you're using the [simplicity example](/osemosys/simplicity), then you should be running only the second command: `otoole convert datapackage datafile https://zenodo.org/record/3479823/files/OSeMOSYS/simplicity-v0.1.zip ./simplicity.txt`

**Comment by fkanyako** [comment] 2019-12-12 18:51
Hi,
I am using the simplicity example, following the replied you gave me before in 
Duplicate of #26.

I downloaded all the simplicity files and replaced the content with my model.
When I type the following command, I get this error:
"""
(myenv) C:\Users\Baker Lab 2\Desktop\WAPOWER>otoole convert datapackage datafile simplicity-v0.1a0.zip ECOWAS.txt

Traceback (most recent call last):
  File "c:\anaconda\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\envs\myenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\envs\myenv\Scripts\otoole.exe\__main__.py", line 7, in <module>
  File "c:\anaconda\envs\myenv\lib\site-packages\otoole\cli.py", line 191, in main
    args.func(args)
  File "c:\anaconda\envs\myenv\lib\site-packages\otoole\cli.py", line 96, in conversion_matrix
    create_datafile(args.from_path, args.to_path)
  File "c:\anaconda\envs\myenv\lib\site-packages\otoole\preprocess\narrow_to_datafile.py", line 60, in main
    if resource.check_relations():
  File "c:\anaconda\envs\myenv\lib\site-packages\datapackage\resource.py", line 225, in check_relations
    for row in self.iter(relations=True, foreign_keys_values=foreign_keys_values):
  File "c:\anaconda\envs\myenv\lib\site-packages\tableschema\table.py", line 104, in iter
    for row_number, headers, row in iterator:
  File "c:\anaconda\envs\myenv\lib\site-packages\tableschema\table.py", line 282, in builtin_processor
    row = self.__schema.cast_row(row)
  File "c:\anaconda\envs\myenv\lib\site-packages\tableschema\schema.py", line 147, in cast_row
    raise exceptions.CastError(message)
tableschema.exceptions.CastError: Row length 10 doesn't match fields count 6
"""

Obviously, my model is much bigger than the simplicity example, I have 9 countries for instance. 
How I do fix this problem?

Many thanks

Franklyn

**Comment by willu47** [comment] 2019-12-13 08:10
Hi @fkanyako - this looks like a problem in one of the CSV files, where you have extra commas in one row so that it has 10 fields rather than the 6 expected from the headers.

This must be one of `InputActivitityRatio`, `OutputActivityRatio` or `EmissionActivityRatio` as these are the only files with 6 columns.

**Comment by fkanyako** [comment] 2019-12-13 18:57
Thank you, this violation has been fixed. But there is another one I have struggled to fixed. 

(myenv) C:\Users\Baker Lab 2\Desktop\WAPOWER>otoole convert datapackage datafile simplicity-v0.1a0.zip  ./simplicity.txt
Traceback (most recent call last):
  File "c:\anaconda\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\envs\myenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\envs\myenv\Scripts\otoole.exe\__main__.py", line 7, in <module>
  File "c:\anaconda\envs\myenv\lib\site-packages\otoole\cli.py", line 191, in main
    args.func(args)
  File "c:\anaconda\envs\myenv\lib\site-packages\otoole\cli.py", line 96, in conversion_matrix
    create_datafile(args.from_path, args.to_path)
  File "c:\anaconda\envs\myenv\lib\site-packages\otoole\preprocess\narrow_to_datafile.py", line 60, in main
    if resource.check_relations():
  File "c:\anaconda\envs\myenv\lib\site-packages\datapackage\resource.py", line 225, in check_relations
    for row in self.iter(relations=True, foreign_keys_values=foreign_keys_values):
  File "c:\anaconda\envs\myenv\lib\site-packages\tableschema\table.py", line 147, in iter
    raise exceptions.RelationError(message)
tableschema.exceptions.RelationError: Foreign key "['YEAR']" violation in row "2": ('2019',) not found in YEAR

I have checked each of my time-dependent csvs to make sure that 2019 is in there, both manually and also with a function. However, I still get this error. Most strenuous is that I can't locate which csv file this error is coming from.

Thank you for your help.

Franklyn

**Comment by willu47** [comment] 2019-12-16 23:04
@fkanyako - I've now added better error messages for validation errors such as the ones your are experiencing.  Please update your installation of *otoole* to v0.5.2 using `pip install otoole --upgrade`

**Comment by fkanyako** [comment] 2019-12-17 00:30
Thank you so much, it worked perfectly.  zero error.

**Closed** 2019-12-26 16:30 UTC
Labels: question
